version: "2.2"

services:
    flask:
        build:
            context: .
            dockerfile: ./Dockerfile
        image: scetts/tts-test-server:v1
        cpus: 1
        restart: unless-stopped
        environment:
            - "TTS_MODEL_FILE=/content/models/glowtts-v2/best_model.pth.tar"
            - "TTS_MODEL_CONFIG=/content/models/glowtts-v2/config.json"
        volumes:
            - "./data/src/flask:/content/src/flask"
            - "./data/models:/content/models"
        ports: 
            - "4000:4000"